name: test all binaries

permissions:
  contents: read

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: get tools versions
              uses: sudo-bot/action-shunit2@latest
              with:
                  cli: "docker/tests/versions.sh"
